# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-07 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('frame', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('frame', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=5, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('way', models.CharField(blank=True, max_length=5, null=True)),
                ('shape', models.CharField(blank=True, max_length=10, null=True)),
                ('mid', models.IntegerField(blank=True, null=True)),
                ('why', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frameStart', models.IntegerField()),
                ('frameEnd', models.IntegerField()),
                ('numRounds', models.IntegerField()),
                ('numP1wins', models.IntegerField()),
                ('numP2wins', models.IntegerField()),
                ('numTies', models.IntegerField()),
                ('numP1missiles', models.IntegerField()),
                ('numP2missiles', models.IntegerField()),
                ('p1score', models.IntegerField()),
                ('p2score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('numGames', models.IntegerField()),
                ('numWins', models.IntegerField()),
                ('numLosses', models.IntegerField()),
                ('numTies', models.IntegerField()),
                ('numMissiles', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frameStart', models.IntegerField()),
                ('frameEnd', models.IntegerField()),
                ('numP1win', models.BooleanField()),
                ('numP2win', models.BooleanField()),
                ('numTie', models.BooleanField()),
                ('numP1missiles', models.IntegerField()),
                ('numP2missiles', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agora_spacewar.Game')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1rounds', to='agora_spacewar.Player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2rounds', to='agora_spacewar.Player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1games', to='agora_spacewar.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2games', to='agora_spacewar.Player'),
        ),
        migrations.AddField(
            model_name='event',
            name='mteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missile_events', to='agora_spacewar.Player'),
        ),
        migrations.AddField(
            model_name='event',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agora_spacewar.Player'),
        ),
        migrations.AddField(
            model_name='event',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agora_spacewar.Round'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agora_spacewar.Game'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agora_spacewar.Player'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agora_spacewar.Round'),
        ),
    ]
