# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-07 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora_spacewar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='frameStart',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='numP1missiles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='numP1wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='numP2missiles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='numP2wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='numTies',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='p1score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='p2score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='numGames',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='numLosses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='numMissiles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='numTies',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='numWins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='round',
            name='numP1missiles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='round',
            name='numP1win',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='round',
            name='numP2missiles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='round',
            name='numP2win',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='round',
            name='numTie',
            field=models.BooleanField(default=0),
        ),
    ]
