# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-07 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agora_spacewar', '0002_auto_20161107_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='numP1missiles',
            new_name='p1missiles',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='numP1win',
            new_name='p1win',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='numP2missiles',
            new_name='p2missiles',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='numP2win',
            new_name='p2win',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='numTie',
            new_name='tie',
        ),
    ]
