# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-07 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agora_spacewar', '0003_auto_20161107_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='numP1missiles',
            new_name='p1missiles',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='numP1wins',
            new_name='p1wins',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='numP2missiles',
            new_name='p2missiles',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='numP2wins',
            new_name='p2wins',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='numTies',
            new_name='ties',
        ),
    ]
