# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-07 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agora_spacewar', '0004_auto_20161107_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='name',
        ),
        migrations.AddField(
            model_name='achievement',
            name='template',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='agora_spacewar.AchievementTemplate'),
            preserve_default=False,
        ),
    ]
